CHANGELOG.md
ruby/lib/shared_examples.rb

Fix situation where the message types were all being flagged as `attachment`
Fix #39 
New sample output
```
0> original_messages_types
=> [:meta, :source, :gherkin_document, :pickle, :pickle, :pickle, :pickle, :pickle, :pickle, :pickle, :pickle, :step_definition, :step_definition, :step_definition, :step_definition, :step_definition, :step_definition, :step_definition, :step_definition, :step_definition, :hook, :test_run_started, :test_case, :test_case, :test_case, :test_case, :test_case, :test_case, :test_case, :test_case, :test_case_started, :test_step_started, :test_step_finished, :test_step_started, :attachment, :test_step_finished, :test_case_finished, :test_case_started, :test_step_started, :test_step_finished, …
```

Ruby: Fix CCK only reporting messages as `attachment`

---

ruby/lib/keys_checker.rb
ruby/spec/messages_comparator_spec.rb

Add a test and new functionality to ignore **both** extra and missing keys that are of the Meta Envelope
Fixes #41 
- 
----

Ruby: ignore meta ci messages in testing

---

.github/workflows/release-ruby.yml
.github/workflows/test-ruby.yml
CHANGELOG.md
ruby/Gemfile
ruby/cucumber-compatibility-kit.gemspec

Improve workflows / ruby versions
- :boom: Breaking change (incompatible changes to the API) - Will facilitate a new major
----

Ruby: bump workflows

---

CHANGELOG.md
ruby/lib/keys_checker.rb
ruby/spec/keys_checker_spec.rb
ruby/spec/messages_comparator_spec.rb

Optimise #compare and reduce complexity. Fixes #42 
----

[Ruby]: Optimise KeysChecker#compare

---

CONTRIBUTING.md
README.md

Add a section to the README about how to adopt the compatibility kit in your Cucumber implementation. Move the contributing docs to the standard file for clarity.
----

chore: add docs for adoption

---

ruby/features/attachments/attachments.feature.rb

For filename attachments we need to pass in a custom filename occassionally, so duplicate the  name or pass in the name
Fixes an issue I forgot to fix in the big cck conformance changes
Not fixing `#embed` usage as this will be removed at some point soon as we look to couple the cck to a few versions of ruby
----

[Ruby]: Fix #attach_or_embed to work with var args

---

ruby/lib/cck/messages_comparator.rb

Fix a situation where we were incorrectly checking `Ci` messages
Don't check `Git` message properties, as these can vary (The NDJSON generation won't have a branch, but every CI run **will** have a branch)
Get cucumber-ruby conformant
----

[Ruby] bugfix: Don't check `git` sub-messages

---

devkit/samples/stack-traces/stack-traces.feature
ruby/features/stack-traces/stack-traces.feature.rb

`stack-traces` now is consistent for ruby/js
Do we need to fix anything else (I'm deliberately not regenerating the ndjson yet because there are a bunch of these that will need re-generating each time). 
To avoid conflicts I'll re-generate once after merging several of these fixes
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template …

CCK: reconcile stack-traces

---

devkit/samples/skipped/skipped.feature
devkit/samples/skipped/skipped.feature.ts
ruby/features/skipped/skipped.feature.rb

`skipped` now is consistent for ruby/js
Do we need to fix anything else (I'm deliberately not regenerating the ndjson yet because there are a bunch of these that will need re-generating each time). 
To avoid conflicts I'll re-generate once after merging several of these fixes
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template …

CCK: reconcile skipped

---

devkit/samples/examples-tables/examples-tables.feature

`examples-tables` are now is consistent for ruby/js. EDIT: No code change here out of feature
----

CCK: Reconcile examples tables

---

devkit/samples/retry/retry.feature
ruby/features/retry/retry.feature.rb

`retry` is now is consistent for ruby (No JS changes needed).
- 
----

CCK: Reconcile retry

---

devkit/samples/cdata/cdata.feature
devkit/samples/data-tables/data-tables.feature

`data-tables` are now is consistent for ruby/js. EDIT: No code change here out of feature
----

CCK: Reconcile data tables

---

devkit/samples/minimal/minimal.feature.ts
ruby/features/minimal/minimal.feature.rb

`minimal` is now is consistent for ruby/js.
----

CCK: Reconcile minimal

---

devkit/samples/cdata/cdata.feature.ts
ruby/features/cdata/cdata.feature.rb

`cdata` now is consistent for ruby/js. NB: It was missing for ruby!
Do we need to fix anything else (I'm deliberately not regenerating the ndjson yet because there are a bunch of these that will need re-generating each time). 
To avoid conflicts I'll re-generate once after merging several of these fixes
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template …

CCK: Reconcile cdata

---

devkit/samples/pending/pending.feature
devkit/samples/pending/pending.feature.ts
ruby/features/pending/pending.feature.rb

`pending` is now is consistent for ruby/js.
----

CCK: Reconcile pending

---

devkit/samples/parameter-types/parameter-types.feature
devkit/samples/parameter-types/parameter-types.feature.ts
ruby/features/parameter-types/parameter-types.feature.rb

`parameter-types` is now is consistent for ruby/js.
----

CCK: Reconcile parameter types

---

devkit/samples/attachments/attachments.feature
devkit/samples/attachments/attachments.feature.ts
ruby/features/attachments/attachments.feature.rb

`attachments` are now is consistent for ruby/js.
Do we need to fix anything else (I'm deliberately not regenerating the ndjson yet because there are a bunch of these that will need re-generating each time). 
To avoid conflicts I'll re-generate once after merging several of these fixes
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template …

CCK: Reconcile attachments

---

devkit/samples/hooks/hooks.feature
devkit/samples/hooks/hooks.feature.ts
devkit/samples/pending/pending.feature
ruby/features/hooks/hooks.feature.rb

`hooks` is now is consistent for ruby/js.
----

CCK: Reconcile hooks

---

devkit/samples/rules/rules.feature
devkit/samples/rules/rules.feature.ts
ruby/features/rules/rules.feature.rb

`rules` is now is consistent for ruby/js.
I also massively removed the contradictory steps. Now it's at least consistent.
----

CCK: Reconcile rules

---

ruby/lib/cck/examples.rb

The way ruby is autoloading code it's causing a method conflict. So just use 2 diff names.
We want to have the same namespace (Although maybe we shouldn't). So for now this will load the path in 2 diff ways (Intended)
----

hotfix: Avoid confusing path situation where no CCK tests are found

---

CHANGELOG.md
devkit/samples/hooks-attachment/.gitattributes

Inform git that line endings in `cucumber.svg` should not be changed. 
SVG files are plain text. So git will change line endings on windows.
Because we expect the image to have been encoded in base64 with `lf` rather than
`crlf` this is not desirable.
See for example: https://github.com/cucumber/cucumber-jvm/actions/runs/13509886103/job/37747778780?pr=2977

Do not allow Git to change line endings in SVG images
